<div class="mb-4 grid gap-4 sm:grid-cols-2">
    <label class="text-sm"><span class="mb-1 block font-medium text-slate-700">City</span><select class="w-full rounded border border-slate-300 px-3 py-2" name="city_id" required><option value="">Select city</option>@foreach ($cities as $city)<option value="{{ $city->getKey() }}" @selected((string) old('city_id', $neighborhood->getAttribute('city_id')) === (string) $city->getKey())>{{ $city->getAttribute('name_fa') }} · {{ $city->getAttribute('code') }}</option>@endforeach</select></label>
    <label class="text-sm"><span class="mb-1 block font-medium text-slate-700">Type</span><select class="w-full rounded border border-slate-300 px-3 py-2" name="type" required>@foreach ($types as $type)<option value="{{ $type }}" @selected(old('type', $neighborhood->getAttribute('type') ?: 'neighborhood') === $type)>{{ $type }}</option>@endforeach</select></label>
    <label class="text-sm"><span class="mb-1 block font-medium text-slate-700">Default region</span><select class="w-full rounded border border-slate-300 px-3 py-2" name="default_city_region_id"><option value="">None</option>@foreach ($regions as $region)<option value="{{ $region->getKey() }}" @selected((string) old('default_city_region_id', $neighborhood->getAttribute('default_city_region_id')) === (string) $region->getKey())>{{ $region->getAttribute('name_fa') }} · {{ $region->getAttribute('code') }}</option>@endforeach</select></label>
    <label class="text-sm"><span class="mb-1 block font-medium text-slate-700">Default area</span><select class="w-full rounded border border-slate-300 px-3 py-2" name="default_city_area_id"><option value="">None</option>@foreach ($areas as $area)<option value="{{ $area->getKey() }}" @selected((string) old('default_city_area_id', $neighborhood->getAttribute('default_city_area_id')) === (string) $area->getKey())>{{ $area->getAttribute('name_fa') }} · {{ $area->getAttribute('code') }}</option>@endforeach</select></label>
</div>
@include('iran-locations::admin.partials.location-fields', ['model' => $neighborhood])
<div class="mt-4 grid gap-4 sm:grid-cols-2">
    <label class="text-sm"><span class="mb-1 block font-medium text-slate-700">Latitude</span><input class="w-full rounded border border-slate-300 px-3 py-2" name="latitude" value="{{ old('latitude', $neighborhood->getAttribute('latitude')) }}"></label>
    <label class="text-sm"><span class="mb-1 block font-medium text-slate-700">Longitude</span><input class="w-full rounded border border-slate-300 px-3 py-2" name="longitude" value="{{ old('longitude', $neighborhood->getAttribute('longitude')) }}"></label>
</div>
