<?php

declare(strict_types=1);

namespace Zarbin\IranLocations\Tests\Unit;

use Zarbin\IranLocations\Tests\TestCase;

class PublicDocumentationTest extends TestCase
{
    public function test_public_documentation_files_exist(): void
    {
        foreach ($this->publicDocumentationFiles() as $file) {
            self::assertFileExists($this->path($file));
        }
    }

    public function test_public_documentation_avoids_process_wording(): void
    {
        $blocked = [
            'generated by AI',
            'Codex',
            'Phase ',
            'this phase',
            'roadmap prompt',
            'implementation phase',
            'micro-patch',
            'internal review',
            'upload zip',
            'AI-generated',
        ];

        foreach ($this->publicDocumentationFiles() as $file) {
            $contents = file_get_contents($this->path($file));

            self::assertIsString($contents);

            foreach ($blocked as $phrase) {
                self::assertStringNotContainsString($phrase, $contents, "{$file} contains blocked wording [{$phrase}].");
            }
        }
    }

    public function test_persian_readme_documents_primary_usage_and_data_scope(): void
    {
        $readme = file_get_contents($this->path('README.md'));

        self::assertIsString($readme);
        self::assertStringContainsString('Laravel Iran Locations', $readme);
        self::assertStringContainsString('زبان‌ها: فارسی', $readme);
        self::assertStringContainsString('[English](README.en.md)', $readme);
        self::assertStringContainsString('JSON driver', $readme);
        self::assertStringContainsString('database driver', $readme);
        self::assertStringContainsString('بدون migration', $readme);
        self::assertStringContainsString('کدهای عمومی', $readme);
        self::assertStringContainsString('p.01', $readme);
        self::assertStringContainsString('s.01.01.01.01', $readme);
        self::assertStringContainsString('31 استان', $readme);
        self::assertStringContainsString('484 شهرستان', $readme);
        self::assertStringContainsString('1087 بخش', $readme);
        self::assertStringContainsString('1456 شهر', $readme);
        self::assertStringContainsString('568 محله یا مکان شهری تهران', $readme);
        self::assertStringContainsString('جدول‌ها را truncate نمی‌کند', $readme);
        self::assertStringContainsString('رکوردهای `source = custom` حفظ می‌شوند', $readme);
        self::assertStringContainsString('zarbinco/laravel-persian-core', $readme);
    }

    public function test_english_readme_documents_release_safety_and_data_scope(): void
    {
        $readme = file_get_contents($this->path('README.en.md'));

        self::assertIsString($readme);
        self::assertStringContainsString('Languages: [فارسی](README.md) | English', $readme);
        self::assertStringContainsString('The Persian README is the primary GitHub documentation.', $readme);
        self::assertStringContainsString('31 provinces', $readme);
        self::assertStringContainsString('484 counties', $readme);
        self::assertStringContainsString('1087 official districts', $readme);
        self::assertStringContainsString('1456 cities', $readme);
        self::assertStringContainsString('568 Tehran neighborhood', $readme);
        self::assertStringContainsString('never truncates', $readme);
        self::assertStringContainsString('Custom records are preserved', $readme);
        self::assertStringContainsString('read-only JSON driver', $readme);
        self::assertStringContainsString('database IDs', $readme);
    }

    public function test_public_documentation_avoids_removed_config_keys_and_private_paths(): void
    {
        $blockedPatterns = [
            'removed sync normalization key' => '/normalization\.on_sync/',
            'removed custom preservation key' => '/data\.preserve_custom_records/',
            'drive-letter local path' => '/[A-Z]:\//',
            'mounted temp path' => '#/'.'mnt/data#',
            'local stack path' => '/\b(?:'.'lara'.'gon|x'.'ampp)\b/i',
        ];

        foreach ($this->publicDocumentationFiles() as $file) {
            $contents = file_get_contents($this->path($file));

            self::assertIsString($contents);

            foreach ($blockedPatterns as $label => $pattern) {
                self::assertDoesNotMatchRegularExpression($pattern, $contents, "{$file} contains {$label}.");
            }
        }
    }

    public function test_release_docs_reference_release_gate_and_placeholder_smoke_path(): void
    {
        $checklist = file_get_contents($this->path('docs/release-checklist.md'));
        $smoke = file_get_contents($this->path('docs/consumer-smoke-test.md'));

        self::assertIsString($checklist);
        self::assertIsString($smoke);
        self::assertStringContainsString('composer run-script release:check', $checklist);
        self::assertStringContainsString('tools/check-archive.php <archive.zip>', $checklist);
        self::assertStringContainsString('/absolute/path/to/laravel-iran-locations', $smoke);
        self::assertStringContainsString('rm -rf iran-locations-smoke', $smoke);
    }

    public function test_consumer_smoke_components_use_code_based_examples(): void
    {
        $smoke = file_get_contents($this->path('docs/consumer-smoke-test.md'));

        self::assertIsString($smoke);
        self::assertStringContainsString('name="province_code"', $smoke);
        self::assertStringContainsString('name="city_code"', $smoke);
        self::assertStringContainsString('province-code="p.01"', $smoke);
        self::assertStringContainsString('city-code="s.01.01.01.01"', $smoke);
        self::assertStringContainsString('ID-based names and parent props are database-driver-only.', $smoke);
        self::assertStringNotContainsString('<x-iran-locations::province-select name="province_id" />', $smoke);
        self::assertStringNotContainsString('<x-iran-locations::city-select name="city_id" />', $smoke);
    }

    /**
     * @return array<int, string>
     */
    private function publicDocumentationFiles(): array
    {
        return [
            'README.md',
            'README.en.md',
            'CHANGELOG.md',
            'CONTRIBUTING.md',
            'DATA-SOURCES.md',
            'DATA-LICENSE.md',
            'SECURITY.md',
            'LICENSE.md',
            'docs/data.md',
            'docs/sync.md',
            'docs/admin.md',
            'docs/api.md',
            'docs/query-examples.md',
            'docs/components.md',
            'docs/extending.md',
            'docs/consumer-smoke-test.md',
            'docs/release-checklist.md',
        ];
    }

    private function path(string $file): string
    {
        return dirname(__DIR__, 2).'/'.$file;
    }
}
