<?php

declare(strict_types=1);

namespace Zarbin\IranLocations\Tests\Unit;

use Zarbin\IranLocations\Tests\TestCase;

class PublicDocumentationTest extends TestCase
{
    public function test_public_documentation_files_exist(): void
    {
        foreach ($this->publicDocumentationFiles() as $file) {
            self::assertFileExists($this->path($file));
        }
    }

    public function test_public_documentation_avoids_process_wording(): void
    {
        $blocked = [
            'generated by AI',
            'Codex',
            'Phase ',
            'this phase',
            'roadmap prompt',
            'implementation phase',
            'micro-patch',
            'internal review',
            'upload zip',
            'AI-generated',
        ];

        foreach ($this->publicDocumentationFiles() as $file) {
            $contents = file_get_contents($this->path($file));

            self::assertIsString($contents);

            foreach ($blocked as $phrase) {
                self::assertStringNotContainsString($phrase, $contents, "{$file} contains blocked wording [{$phrase}].");
            }
        }
    }

    public function test_readme_documents_release_safety_and_data_scope(): void
    {
        $readme = file_get_contents($this->path('README.md'));

        self::assertIsString($readme);
        self::assertStringContainsString('Laravel Iran Locations', $readme);
        self::assertStringContainsString('31 provinces', $readme);
        self::assertStringContainsString('484 counties', $readme);
        self::assertStringContainsString('1087 official districts', $readme);
        self::assertStringContainsString('1456 cities', $readme);
        self::assertStringContainsString('568 Tehran neighborhood', $readme);
        self::assertStringContainsString('never truncates', $readme);
        self::assertStringContainsString('Custom records are preserved', $readme);
        self::assertStringContainsString('zarbinco/laravel-persian-core', $readme);
    }

    /**
     * @return array<int, string>
     */
    private function publicDocumentationFiles(): array
    {
        return [
            'README.md',
            'CHANGELOG.md',
            'CONTRIBUTING.md',
            'SECURITY.md',
            'LICENSE.md',
            'docs/data.md',
            'docs/sync.md',
            'docs/admin.md',
            'docs/api.md',
            'docs/components.md',
            'docs/extending.md',
            'docs/release-checklist.md',
        ];
    }

    private function path(string $file): string
    {
        return dirname(__DIR__, 2).'/'.$file;
    }
}
